### ISSUE TITLE
Wrong solution for ques 4

### ISSUE THREAD

**Issue by Ojasv-Singh** [sparkcoder157/Credit-Suisse-Solution#1]
Hi... the sol for ques4 is failing some test cases... Do you have any idea how do it? Thanks

**Comment by TheLazy-Dev** [comment]
Can you provide an exact count of how many test cases are failing? As for me 11 cases failed yet it was successfully submitted. 
Sorry for the late reply.

**Comment by Inderjeet-123** [comment]
ya there is some issue in the compiler as same code is passing sometim 80 tstcase sometimes 81
